name: Deploy to GitHub pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:

    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2

    # sets up .NET Core SDK 5.0.x
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish BlazorWeb/BlazorWeb.csproj -c Release -o release --nologo
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Push to GitHub page repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
      with:
        source-directory: 'release/wwwroot'
        destination-github-username: 'legendsayantan'
        destination-repository-name: 'legendsayantan.github.io'
        target-branch: main
    # - name: Push to is-a.dev repository 
    #   uses: cpina/github-action-push-to-another-repository@main
    #   env:
    #     API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
    #   with:
    #     source-directory: 'release/wwwroot'
    #     destination-github-username: 'legendsayantan'
    #     destination-repository-name: 'legendsayantan.is-a.dev'
    #     target-branch: main
    - name: Setup workflows on github.io repository 
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
      with:
        source-directory: .push/.github/
        target-directory: .github/
        destination-github-username: 'legendsayantan'
        destination-repository-name: 'legendsayantan.github.io'
        target-branch: main
    # - name: Setup workflows on is-a.dev repository 
    #   uses: cpina/github-action-push-to-another-repository@main
    #   env:
    #     API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
    #   with:
    #     source-directory: .push/.github/
    #     target-directory: .github/
    #     destination-github-username: 'legendsayantan'
    #     destination-repository-name: 'legendsayantan.is-a.dev'
    #     target-branch: main
